name: E2E-test

on:
  push:
    branches:
      - main

env:
  MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
  MYSQL_DATABASE: ${{ secrets.DB_NAME }}
  DB_HOST: mysql
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}

jobs:
  build_application:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Check out code 
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the docker-compose stack
      run: |
        docker compose up -d --build 
        docker ps
        until [ "$(docker inspect -f '{{.State.Health.Status}}' entryTracker-db)" = "healthy" ]; do
        echo "Waiting for MySQL..."
        sleep 2
        done
        
    # - name: Check mysql-container
    #   run: |
    #     docker ps &
    #     npx wait-on http://localhost:5000 & 
    #     npx wait-on http://localhost:3366 &
    #     curl http://localhost:5000

    - name: Stop containers
      if: always()
      run: docker compose down 
