name: E2E-test

on:
  push:
    branches:
      - main


env:
  MYSQL_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
  MYSQL_DATABASE: ${{ secrets.DB_NAME }}
  DB_HOST: mysql
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}

  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  ECR_REPOSITORY: middle-task/entrytracker

permissions:
  contents: read
  packages: write
  id-token: write


jobs:
  build_and_package_application:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Check out code 
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the docker-compose stack
      run: |
        docker compose up -d --build 
        docker ps
        until [ "$(docker inspect -f '{{.State.Health.Status}}' entryTracker-db)" = "healthy" ]; do
        echo "Waiting for MySQL..."
        sleep 2
        done
        curl http://localhost:5000

    - name: Export image
      run: docker save entrytracker:latest -o image.tar
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: image.tar

    - name: Stop containers
      if: always()
      run: docker compose down -v

  publish_to_ecr:
    needs: build_and_package_application
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Authenticate Docker to AWS ECR
      run: |
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
        docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image
    
    - name: Load image
      run: docker load -i image.tar

    - name: Tag image
      run: |
        docker tag entrytracker:latest \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/middle-task/entrytracker:latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
        echo "✓ Image pushed to ECR"
